server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(html|js|css|json|png|jpg|jpeg|gif|webp|svg|ico|mp3|wav|ogg|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
